### ISSUE TITLE
FileNotFoundError with --multifile

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#176]
```
% ../feditest/venv.darwin.develop/bin/feditest convert-transcript --in production/testresults/webfinger-server-all-wellknown-saas-imp.json --multifile foo
Traceback (most recent call last):
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/cli/commands/convert_transcript.py", line 53, in run
    serializer.write(transcript)
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/testruntranscript.py", line 581, in write
    self._copy_static_files(self.template_path, self.output_dir)
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/testruntranscript.py", line 656, in _copy_static_files
    shutil.copyfile(filepath_from, filepath_to)
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shutil.py", line 262, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'foo/foo/css/feditest.css'
```

It might be that the `chdir` gets in the way: https://github.com/fediverse-devnet/feditest/blob/b6a324b393ff601b736d5d50ef7fc099e5a0d176/src/feditest/testruntranscript.py#L578

**Comment by steve-bate** [comment]
I didn’t test this with a relative output directory. Do you want to make the change or wait until I have some time to do it. Just removing the `chdir` is likely to cause issues with relative template resolution but maybe that can handled by resolving all template directories in the path to absolute paths.

**Comment by jernst** [comment]
Still having (different) trouble:

```
% ../feditest/venv.darwin.develop/bin/feditest convert-transcript --in production/testresults/webfinger-server-all-wellknown-saas-imp.json --multifile foo
Traceback (most recent call last):
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/cli/commands/convert_transcript.py", line 53, in run
    serializer.write(transcript)
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/testruntranscript.py", line 612, in write
    fp.write(matrix_template.render(**context))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/feditest/templates/multifile/test_matrix.jinja2", line 15, in top-level template code
    {%  include "testrun-transcript-title.jinja2" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jernst/git/github.com/jernst/feditest/venv.darwin.develop/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: testrun-transcript-title.jinja2
```
Could this exception have a message saying where it was looking for templates and couldn't find them?

**Comment by steve-bate** [comment]
> Still having (different) trouble:

Maybe we should create a different issue for this?

> Could this exception have a message saying where it was looking for templates and couldn't find them?

It's a jinja2 exception, raised by the jinja2 template loader. You didn't specify a template directory so it's going to look in `templates/multifile`, by default. Is that where the templates are located? If not, use the --template argument to specify the directory where they're located.

**Comment by jernst** [comment]
Separate issue created: #179. 
Also, we probably need: #180.
