### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#219]
Remove the stack trace here and improve the error message.

```
2024-07-10T13:50:05Z [ERROR] feditest: Ended TestRunSession Mastodon (local, UBOS) with Exception:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/feditest/testrun.py", line 314, in run
    self.run_constellation.setup()
  File "/opt/homebrew/lib/python3.11/site-packages/feditest/testrun.py", line 69, in setup
    node : Node = node_driver.provision_node(plan_role_name, parameters)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/feditest/protocols/__init__.py", line 104, in provision_node
    ret = self._provision_node(rolename, parameters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/feditest/ubos/__init__.py", line 24, in _provision_node
    raise OSError(f'{ type(self).__name__ } requires UBOS Gears (see ubos.net).')
OSError: MastodonUbosNodeDriver requires UBOS Gears (see ubos.net).
```

**Comment by jernst** [comment]
Fixed in #228
