### ISSUE TITLE
Errors on Kali Linux

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#420]
It was reported that:

debian-12 3.11.2 (works)
kali 3.12.7 (errors below)

```
Traceback (most recent call last):
  File "/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/cli/__init__.py", line 38, in main
    ret = cmds[cmd_name].run(parser, args, remaining)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/cli/commands/list_tests.py", line 20, in run
    feditest.load_tests_from(args.testsdir)
  File "/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/__init__.py", line 54, in load_tests_from
    load_python_from(dirs, True)
  File "/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/utils.py", line 173, in load_python_from
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/user/ROS/feditest/feditest-local/feditest-tests-fediverse/tests/system3/delete_double_hop.py", line 4, in <module>
    from feditest import poll_but_not, poll_until, step, test
ImportError: cannot import name 'poll_but_not' from 'feditest' (/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/__init__.py)
2024-12-09T21:30:04Z [CRITICAL] feditest: <class 'ImportError'> -- cannot import name 'poll_but_not' from 'feditest' (/home/user/ROS/feditest/feditest-local/lib/python3.12/site-packages/feditest/__init__.py)Traceback (most recent call last):
```

**Comment by jernst** [comment]
Cannot reproduce. Closing.
