### ISSUE TITLE
Tap report should only show tap, not the exceptions

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#76]
E.g. currently:

```
% cd feditest-tests-sandbox jernst$ ../feditest/venv/bin/feditest run --tap
2024-05-01T17:08:52Z [ERROR] feditest: FAILED test assertion: sandbox.example_test_with_functions::example_test2: 
Expected: <-56>
     but: was <0>
 Traceback (most recent call last):

  File "/Users/jernst/git/github.com/fediverse-devnet/feditest/venv/lib/python3.12/site-packages/feditest/__init__.py", line 91, in run
    self.test_function(**args)

  File "/Users/jernst/git/github.com/fediverse-devnet/feditest-tests-sandbox/tests/sandbox/example_test_with_functions.py", line 51, in example_test2
    assert_that(c, equal_to(-56))

  File "/Users/jernst/git/github.com/fediverse-devnet/feditest/venv/lib/python3.12/site-packages/hamcrest/core/assert_that.py", line 58, in assert_that
    _assert_match(actual=actual_or_assertion, matcher=matcher, reason=reason)

  File "/Users/jernst/git/github.com/fediverse-devnet/feditest/venv/lib/python3.12/site-packages/hamcrest/core/assert_that.py", line 73, in _assert_match
    raise AssertionError(description)

AssertionError: 
Expected: <-56>
     but: was <0>


TAP version 14
# test plan: None
# session: session_0
# constellation: A_vs_1
#   name: A_vs_1
#   roles:
#     - name: client
#       driver: sandbox.SandboxMultClientDriver_ImplementationA
#     - name: server
#       driver: sandbox.SandboxMultServerDriver_Implementation1
ok 1 - sandbox.example_test_with_functions::example_test1
ok 2 - sandbox.example_test_with_functions::example_test2
ok 3 - sandbox.example_test_with_classes::ExampleTest1
# session: session_1
# constellation: A_vs_2
#   name: A_vs_2
#   roles:
#     - name: client
#       driver: sandbox.SandboxMultClientDriver_ImplementationA
#     - name: server
#       driver: sandbox.SandboxMultServerDriver_Implementation2Faulty
ok 4 - sandbox.example_test_with_functions::example_test1
not ok 5 - sandbox.example_test_with_functions::example_test2
  ---
  problem: |
    Expected: <-56>
         but: was <0>
  ...
ok 6 - sandbox.example_test_with_classes::ExampleTest1
1..6
# test run summary:
#   total: 6
#   passed: 5
#   failed: 1
#   skipped: 0
```

Everything before `TAP version 14` should go.

**Comment by steve-bate** [comment]
To be clear, the "--tap" option (without an output destination) simply includes the TAP report in the logged output along with whatever else is logged. In this case, the exception stack trace is being logged by the test runner and not the report generator

```python

    def run(self, test_spec: TestPlanTestSpec, session: TestRunSession):
        """
        Run this test in the provided constellation.
        """
...
        try:
            self.test_function(**args)

        except AssertionError as e:
            problem = TestFunctionProblem(test_spec, e)
--->        error('FAILED test assertion:', problem, "\n".join(traceback.format_exception(problem.exc)))
            session.problems.append(problem)
```

If you want *only* the TAP report, you can specify a destination for writing a file. For example,

```
feditest run --tap tap-results.txt
```
The `tap-results.txt` file will have only the TAP output and the exception will still be logged to the console.

Maybe the `AssertionError` logging should be conditional based on the verbose flag?

**Comment by jernst** [comment]
> Maybe the AssertionError logging should be conditional based on the verbose flag?

Yes!

**Comment by steve-bate** [comment]
I can look into that option. One possibility is to log the assertion errors to their own logging category and, in the top-level option handling, disable all logging levels for the assertion-related category unless the verbose flag is set.

**Comment by jernst** [comment]
Maybe there is a way to write this to the `TestResultWriter`, which in case of `TapTestResultWriter` swallows it, and in case of `DefaultTestResultWriter` prints it.

**Comment by steve-bate** [comment]
I think we should open a related issue when we decide what to do about various exception types and their relationship to test fail/error statuses.
